package examen1;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Login_Admin = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bt_Login_Admin1 = new javax.swing.JButton();
        bt_Creacion_Admin = new javax.swing.JButton();
        tf_Login_Admin = new javax.swing.JTextField();
        pf_Codigo_Admin = new javax.swing.JPasswordField();
        bt_Volver_Logins = new javax.swing.JButton();
        jd_Admisnistrar = new javax.swing.JDialog();
        bt_Crear_Libro = new javax.swing.JButton();
        bt_Eliminar_Libro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bt_Volver_Login_Admin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jd_Creacion_Libro = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jd_Año_Ingresado = new com.toedter.calendar.JDateChooser();
        jd_Año_Escrito = new com.toedter.calendar.JDateChooser();
        tf_Autor_Principal = new javax.swing.JTextField();
        tf_Titulo = new javax.swing.JTextField();
        tf_Auto_Secunadrio = new javax.swing.JTextField();
        tf_Idioma = new javax.swing.JTextField();
        tf_Editorial = new javax.swing.JTextField();
        tf_ISBN = new javax.swing.JTextField();
        tf_Genero = new javax.swing.JTextField();
        rb_Disponible = new javax.swing.JRadioButton();
        rb_Fuera_de_Inventario = new javax.swing.JRadioButton();
        rb_Prestado = new javax.swing.JRadioButton();
        bt_Crear_Libro1 = new javax.swing.JButton();
        bt_Volver_Administrar = new javax.swing.JButton();
        bg_Estados_Libros = new javax.swing.ButtonGroup();
        jd_Login_Usuario = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bt_Login_Usuario1 = new javax.swing.JButton();
        bt_Creacion_Usuario = new javax.swing.JButton();
        bt_Volver_Login1 = new javax.swing.JButton();
        tf_Login_Usuario = new javax.swing.JTextField();
        pf_Codigo_Usuario = new javax.swing.JPasswordField();
        jd_Libros_Inventario = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Inventario = new javax.swing.JTable();
        bt_Volver_Administar1 = new javax.swing.JButton();
        bt_Limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_Login_Admin = new javax.swing.JButton();
        bt_Login_Usuario = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Login Administrador");

        jLabel4.setText("Nombre");

        jLabel5.setText("Codigo");

        bt_Login_Admin1.setText("Login");
        bt_Login_Admin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Login_Admin1ActionPerformed(evt);
            }
        });

        bt_Creacion_Admin.setText("Crear un admin");

        bt_Volver_Logins.setText("Volver a los Logins");
        bt_Volver_Logins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Volver_LoginsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_Login_AdminLayout = new javax.swing.GroupLayout(jd_Login_Admin.getContentPane());
        jd_Login_Admin.getContentPane().setLayout(jd_Login_AdminLayout);
        jd_Login_AdminLayout.setHorizontalGroup(
            jd_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Login_AdminLayout.createSequentialGroup()
                .addGroup(jd_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Login_AdminLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3))
                    .addGroup(jd_Login_AdminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Login_AdminLayout.createSequentialGroup()
                                .addComponent(bt_Login_Admin1)
                                .addGap(48, 48, 48)
                                .addComponent(bt_Creacion_Admin))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Login_AdminLayout.createSequentialGroup()
                                .addGroup(jd_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jd_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_Login_Admin)
                                    .addComponent(pf_Codigo_Admin))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Volver_Logins)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_Login_AdminLayout.setVerticalGroup(
            jd_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Login_AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addGroup(jd_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_Login_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jd_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pf_Codigo_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jd_Login_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Login_Admin1)
                    .addComponent(bt_Creacion_Admin)
                    .addComponent(bt_Volver_Logins))
                .addGap(56, 56, 56))
        );

        bt_Crear_Libro.setText("Crear Libro");
        bt_Crear_Libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear_LibroActionPerformed(evt);
            }
        });

        bt_Eliminar_Libro.setText("Eliminar Libro");
        bt_Eliminar_Libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Eliminar_LibroActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Administracion de Libros");

        bt_Volver_Login_Admin.setText("Volver al login");
        bt_Volver_Login_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Volver_Login_AdminActionPerformed(evt);
            }
        });

        jButton1.setText("Inventario de Libros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_AdmisnistrarLayout = new javax.swing.GroupLayout(jd_Admisnistrar.getContentPane());
        jd_Admisnistrar.getContentPane().setLayout(jd_AdmisnistrarLayout);
        jd_AdmisnistrarLayout.setHorizontalGroup(
            jd_AdmisnistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdmisnistrarLayout.createSequentialGroup()
                .addGroup(jd_AdmisnistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AdmisnistrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_AdmisnistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_Eliminar_Libro)
                            .addComponent(bt_Crear_Libro)))
                    .addGroup(jd_AdmisnistrarLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel6))
                    .addGroup(jd_AdmisnistrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_Volver_Login_Admin))
                    .addGroup(jd_AdmisnistrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jd_AdmisnistrarLayout.setVerticalGroup(
            jd_AdmisnistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AdmisnistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addComponent(bt_Crear_Libro)
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_Eliminar_Libro)
                .addGap(31, 31, 31)
                .addComponent(bt_Volver_Login_Admin)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Creacion de Libros");

        jLabel8.setText("Autor Principal");

        jLabel10.setText("Autor Secundario");

        jLabel11.setText("Año de Ingreso a la libreria");

        jLabel12.setText("Año que se escribio");

        jLabel13.setText("Titulo");

        jLabel14.setText("Editorial");

        jLabel15.setText("Idioma");

        jLabel17.setText("ISBN");

        jLabel18.setText("Estado ");

        jLabel19.setText("Genero");

        bg_Estados_Libros.add(rb_Disponible);
        rb_Disponible.setSelected(true);
        rb_Disponible.setText("Disponible");

        bg_Estados_Libros.add(rb_Fuera_de_Inventario);
        rb_Fuera_de_Inventario.setText("Fuera de Inventario");

        bg_Estados_Libros.add(rb_Prestado);
        rb_Prestado.setText("Prestado");

        bt_Crear_Libro1.setText("Crear");
        bt_Crear_Libro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Crear_Libro1ActionPerformed(evt);
            }
        });

        bt_Volver_Administrar.setText("Volver a Administrar");
        bt_Volver_Administrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Volver_AdministrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_Creacion_LibroLayout = new javax.swing.GroupLayout(jd_Creacion_Libro.getContentPane());
        jd_Creacion_Libro.getContentPane().setLayout(jd_Creacion_LibroLayout);
        jd_Creacion_LibroLayout.setHorizontalGroup(
            jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                        .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Auto_Secunadrio))
                            .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Titulo))
                            .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Genero))
                            .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Editorial))
                            .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel7))
                            .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Autor_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Idioma)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                        .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Creacion_LibroLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_ISBN))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Creacion_LibroLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jd_Año_Ingresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Creacion_LibroLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(jd_Año_Escrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(rb_Disponible)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_Prestado)
                                .addGap(18, 18, 18)
                                .addComponent(rb_Fuera_de_Inventario))
                            .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                                .addComponent(bt_Crear_Libro1)
                                .addGap(71, 71, 71)
                                .addComponent(bt_Volver_Administrar)))
                        .addGap(0, 131, Short.MAX_VALUE))))
        );
        jd_Creacion_LibroLayout.setVerticalGroup(
            jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Creacion_LibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_Autor_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_Auto_Secunadrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_Editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jd_Año_Escrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(tf_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jd_Año_Ingresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rb_Disponible)
                    .addComponent(rb_Prestado)
                    .addComponent(rb_Fuera_de_Inventario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jd_Creacion_LibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Crear_Libro1)
                    .addComponent(bt_Volver_Administrar))
                .addGap(26, 26, 26))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Login de Usuario");

        jLabel16.setText("Nombre");

        jLabel20.setText("Codigo");

        bt_Login_Usuario1.setText("Login");

        bt_Creacion_Usuario.setText("Crear Usuario");

        bt_Volver_Login1.setText("Volver a Logins");
        bt_Volver_Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Volver_Login1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_Login_UsuarioLayout = new javax.swing.GroupLayout(jd_Login_Usuario.getContentPane());
        jd_Login_Usuario.getContentPane().setLayout(jd_Login_UsuarioLayout);
        jd_Login_UsuarioLayout.setHorizontalGroup(
            jd_Login_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Login_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Login_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Login_UsuarioLayout.createSequentialGroup()
                        .addComponent(bt_Login_Usuario1)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Creacion_Usuario)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Volver_Login1))
                    .addGroup(jd_Login_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Login_UsuarioLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                            .addComponent(pf_Codigo_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_Login_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jd_Login_UsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(tf_Login_Usuario))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jd_Login_UsuarioLayout.setVerticalGroup(
            jd_Login_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Login_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jd_Login_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_Login_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_Login_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(pf_Codigo_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jd_Login_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Login_Usuario1)
                    .addComponent(bt_Creacion_Usuario)
                    .addComponent(bt_Volver_Login1))
                .addGap(67, 67, 67))
        );

        jt_Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Genero", "Editoriales", "Idioma", "Año de Escritura", "ISBN", "Año de Adicion", "Estado ", "Persona Prestado", "Cuenta Prestada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jt_Inventario.setMaximumSize(new java.awt.Dimension(2147483647, 0));
        jScrollPane1.setViewportView(jt_Inventario);
        if (jt_Inventario.getColumnModel().getColumnCount() > 0) {
            jt_Inventario.getColumnModel().getColumn(0).setHeaderValue("Titulo");
            jt_Inventario.getColumnModel().getColumn(1).setHeaderValue("Autor");
            jt_Inventario.getColumnModel().getColumn(2).setHeaderValue("Genero");
            jt_Inventario.getColumnModel().getColumn(3).setHeaderValue("Editoriales");
            jt_Inventario.getColumnModel().getColumn(4).setHeaderValue("Idioma");
            jt_Inventario.getColumnModel().getColumn(5).setHeaderValue("Año de Escritura");
            jt_Inventario.getColumnModel().getColumn(6).setHeaderValue("ISBN");
            jt_Inventario.getColumnModel().getColumn(7).setHeaderValue("Año de Adicion");
            jt_Inventario.getColumnModel().getColumn(8).setHeaderValue("Estado ");
            jt_Inventario.getColumnModel().getColumn(9).setHeaderValue("Persona Prestado");
            jt_Inventario.getColumnModel().getColumn(10).setHeaderValue("Cuenta Prestada");
        }

        bt_Volver_Administar1.setText("Volver a Administrar");
        bt_Volver_Administar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Volver_Administar1ActionPerformed(evt);
            }
        });

        bt_Limpiar.setText("Limpiar Tabla");
        bt_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_Libros_InventarioLayout = new javax.swing.GroupLayout(jd_Libros_Inventario.getContentPane());
        jd_Libros_Inventario.getContentPane().setLayout(jd_Libros_InventarioLayout);
        jd_Libros_InventarioLayout.setHorizontalGroup(
            jd_Libros_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Libros_InventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Libros_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1228, Short.MAX_VALUE)
                    .addGroup(jd_Libros_InventarioLayout.createSequentialGroup()
                        .addComponent(bt_Volver_Administar1)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Limpiar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_Libros_InventarioLayout.setVerticalGroup(
            jd_Libros_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Libros_InventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jd_Libros_InventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Volver_Administar1)
                    .addComponent(bt_Limpiar))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libreria Online");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido al Login");

        jLabel2.setText("10 libros,1 adminstrador y dos usuarios^C ");

        bt_Login_Admin.setText("Login Administrador");
        bt_Login_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Login_AdminActionPerformed(evt);
            }
        });

        bt_Login_Usuario.setText("Login Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(bt_Login_Admin)
                    .addComponent(bt_Login_Usuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addComponent(bt_Login_Admin)
                .addGap(53, 53, 53)
                .addComponent(bt_Login_Usuario)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_Login_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Login_AdminActionPerformed
        // TODO add your handling code here:
        jd_Login_Admin.setModal(true);
        jd_Login_Admin.pack();
        jd_Login_Admin.setLocationRelativeTo(this);
        jd_Login_Admin.setVisible(true);
    }//GEN-LAST:event_bt_Login_AdminActionPerformed

    private void bt_Crear_LibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear_LibroActionPerformed
        // TODO add your handling code here:
        jd_Creacion_Libro.setModal(true);
        jd_Creacion_Libro.pack();
        jd_Creacion_Libro.setLocationRelativeTo(this);
        jd_Creacion_Libro.setVisible(true);
    }//GEN-LAST:event_bt_Crear_LibroActionPerformed

    private void bt_Crear_Libro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Crear_Libro1ActionPerformed
        // TODO add your handling code here:
        String estado = "", nombre_prestado = "", cuenta_prestada = "";
        int numeros = 0, guiones = 0;
        String titulo = "";
        String genero = "";
        String editorial = "";
        String idioma = "";
        Date anio_excribo = new Date();
        String ISBN = "";
        Date anio_Ingreso = new Date();
        String autop = "";
        String autos = "";
        try {
            titulo = tf_Titulo.getText();
            genero = tf_Genero.getText();
            editorial = tf_Editorial.getText();
            idioma = tf_Idioma.getText();
            anio_excribo = jd_Año_Escrito.getDate();
            String c = tf_ISBN.getText();
            String[] t = c.split("-");
            String aux1 = t[0];
            String aux2 = t[1];
            String aux3 = t[2];
            for (int i = 0; i < aux1.length(); i++) {
                if (Character.isDigit(aux1.charAt(i))) {
                    numeros++;
                }
            }
            if (numeros == 4) {
                numeros = 0;
                guiones++;
            }
            for (int i = 0; i < aux2.length(); i++) {
                if (Character.isDigit(aux1.charAt(i))) {
                    numeros++;
                }
            }
            if (numeros == 4) {
                numeros = 0;
                guiones++;
            }
            for (int i = 0; i < aux3.length(); i++) {
                if (Character.isDigit(aux1.charAt(i))) {
                    numeros++;
                }
            }
            if (numeros == 4) {
                numeros = 0;
                guiones++;
            }
            if (guiones == 3) {
                ISBN = tf_ISBN.getText();
            }
            anio_Ingreso = jd_Año_Ingresado.getDate();
            if (rb_Disponible.isSelected()) {
                estado = "Disponible";
                nombre_prestado = "------";
                cuenta_prestada = "0000";
            } else if (rb_Prestado.isSelected()) {
                estado = "Prestado";
                nombre_prestado = JOptionPane.showInputDialog(jd_Creacion_Libro, "Ingrese nombre de la persona a quien se le presto el libro");
                cuenta_prestada = JOptionPane.showInputDialog(jd_Creacion_Libro, "Ingrese cunata de la persona que se presto");
            } else if (rb_Fuera_de_Inventario.isSelected()) {
                estado = "Fuera de Inventario";
                nombre_prestado = "";
                cuenta_prestada = "";
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(jd_Creacion_Libro, "Ocurio un error y no se pudo crear un libro");
        }
        ((Administrador) admins.get(pos)).getInventario().add(new Libros(titulo, genero, editorial, idioma, anio_excribo, ISBN, anio_Ingreso, estado, nombre_prestado, cuenta_prestada));
        libros.add(new Libros(titulo, genero, editorial, idioma, anio_excribo, ISBN, anio_Ingreso, estado, nombre_prestado, cuenta_prestada));
        for (int i = 0; i < libros.size(); i++) {
            if (((Libros) libros.get(i)).getISBN().equals(((Administrador) admins.get(i)).getInventario().get(i).getISBN())) {
                JOptionPane.showMessageDialog(jd_Creacion_Libro, "Ya hay un libro con ese ISBN");
            }
        }
        if (tf_Autor_Principal.getText().equals("")) {
            autop = JOptionPane.showInputDialog(jd_Creacion_Libro, "Ingrese un el nombre del auto principal");
            ((Administrador) admins.get(pos)).getInventario().get(pos).getAutores().add(autop);
        } else {
            autop = tf_Autor_Principal.getText();
            ((Administrador) admins.get(pos)).getInventario().get(pos).getAutores().add(autop);
        }
        autos = tf_Auto_Secunadrio.getText();
        ((Administrador) admins.get(pos)).getInventario().get(pos).getAutores().add(autos);
        for (int i = 0; i < libros.size(); i++) {
            if (((Libros) libros.get(i)).getEstado().equals("Disponible") || ((Libros) libros.get(i)).getEstado().equals("Prestado")) {
                Object[] newrow = {((Libros) libros.get(i)).getTitulo(),
                    ((Libros) libros.get(i)).getAutores(),
                    ((Libros) libros.get(i)).getGenero(),
                    ((Libros) libros.get(i)).getEditorial(),
                    ((Libros) libros.get(i)).getIdioma(),
                    ((Libros) libros.get(i)).getAnio_excribo(),
                    ((Libros) libros.get(i)).getISBN(),
                    ((Libros) libros.get(i)).getAnio_Ingreso(),
                    ((Libros) libros.get(i)).getEstado(),
                    ((Libros) libros.get(i)).getNombre_prestado(),
                    ((Libros) libros.get(i)).getCuenta_prestada()};

                DefaultTableModel modelo = (DefaultTableModel) jt_Inventario.getModel();
                modelo.addRow(newrow);
                jt_Inventario.setModel(modelo);
            }
        }
        tf_Auto_Secunadrio.setText("");
        tf_Autor_Principal.setText("");
        tf_Editorial.setText("");
        tf_Genero.setText("");
        tf_ISBN.setText("");
        tf_Idioma.setText("");
        jd_Año_Escrito.setDate(new Date());
        jd_Año_Ingresado.setDate(new Date());
    }//GEN-LAST:event_bt_Crear_Libro1ActionPerformed

    private void bt_Login_Admin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Login_Admin1ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < admins.size(); i++) {
            if (((Administrador) admins.get(pos)).getCodigo().equals(pf_Codigo_Admin.getText()) && ((Administrador) admins.get(i)).getNombre().equals(tf_Login_Admin.getText())) {
                pos = i;
                jd_Admisnistrar.setModal(true);
                jd_Admisnistrar.pack();
                jd_Admisnistrar.setLocationRelativeTo(this);
                jd_Admisnistrar.setVisible(true);
                jd_Login_Admin.dispose();
                tf_Login_Admin.setText("");
                pf_Codigo_Admin.setText("");
            } else {
                JOptionPane.showMessageDialog(jd_Login_Admin, "Ese administrador no existe");
            }
        }
    }//GEN-LAST:event_bt_Login_Admin1ActionPerformed

    private void bt_Volver_Login_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Volver_Login_AdminActionPerformed
        // TODO add your handling code here:
        jd_Admisnistrar.dispose();
    }//GEN-LAST:event_bt_Volver_Login_AdminActionPerformed

    private void bt_Volver_AdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Volver_AdministrarActionPerformed
        // TODO add your handling code here:
        jd_Creacion_Libro.dispose();
    }//GEN-LAST:event_bt_Volver_AdministrarActionPerformed

    private void bt_Volver_LoginsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Volver_LoginsActionPerformed
        // TODO add your handling code here:
        jd_Login_Admin.dispose();
    }//GEN-LAST:event_bt_Volver_LoginsActionPerformed

    private void bt_Volver_Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Volver_Login1ActionPerformed
        // TODO add your handling code here:
        jd_Login_Usuario.dispose();
    }//GEN-LAST:event_bt_Volver_Login1ActionPerformed

    private void bt_Volver_Administar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Volver_Administar1ActionPerformed
        // TODO add your handling code here:
        jd_Libros_Inventario.dispose();
    }//GEN-LAST:event_bt_Volver_Administar1ActionPerformed

    private void bt_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_LimpiarActionPerformed
        // TODO add your handling code here:
        jt_Inventario.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Titulo", "Autor", "Genero", "Editoriales", "Idioma", "Año de Escritura", "ISBN", "Año de Adicion", "Estado ", "Persona Prestado", "Cuenta Prestada"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_Inventario);

        bt_Volver_Administar1.setText("Volver a Administrar");
        bt_Volver_Administar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Volver_Administar1ActionPerformed(evt);
            }
        });
    }//GEN-LAST:event_bt_LimpiarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jd_Libros_Inventario.setModal(true);
        jd_Libros_Inventario.pack();
        jd_Libros_Inventario.setLocationRelativeTo(this);
        jd_Libros_Inventario.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_Eliminar_LibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Eliminar_LibroActionPerformed
        // TODO add your handling code here:
        int pos1 = Integer.parseInt(JOptionPane.showInputDialog(jd_Admisnistrar, "Ingrese el libro que quiere eliminar"));
        libros.remove(pos1);
        ((Administrador) admins.get(pos)).getInventario().remove(pos1);
    }//GEN-LAST:event_bt_Eliminar_LibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_Estados_Libros;
    private javax.swing.JButton bt_Creacion_Admin;
    private javax.swing.JButton bt_Creacion_Usuario;
    private javax.swing.JButton bt_Crear_Libro;
    private javax.swing.JButton bt_Crear_Libro1;
    private javax.swing.JButton bt_Eliminar_Libro;
    private javax.swing.JButton bt_Limpiar;
    private javax.swing.JButton bt_Login_Admin;
    private javax.swing.JButton bt_Login_Admin1;
    private javax.swing.JButton bt_Login_Usuario;
    private javax.swing.JButton bt_Login_Usuario1;
    private javax.swing.JButton bt_Volver_Administar1;
    private javax.swing.JButton bt_Volver_Administrar;
    private javax.swing.JButton bt_Volver_Login1;
    private javax.swing.JButton bt_Volver_Login_Admin;
    private javax.swing.JButton bt_Volver_Logins;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_Admisnistrar;
    private com.toedter.calendar.JDateChooser jd_Año_Escrito;
    private com.toedter.calendar.JDateChooser jd_Año_Ingresado;
    private javax.swing.JDialog jd_Creacion_Libro;
    private javax.swing.JDialog jd_Libros_Inventario;
    private javax.swing.JDialog jd_Login_Admin;
    private javax.swing.JDialog jd_Login_Usuario;
    private javax.swing.JTable jt_Inventario;
    private javax.swing.JPasswordField pf_Codigo_Admin;
    private javax.swing.JPasswordField pf_Codigo_Usuario;
    private javax.swing.JRadioButton rb_Disponible;
    private javax.swing.JRadioButton rb_Fuera_de_Inventario;
    private javax.swing.JRadioButton rb_Prestado;
    private javax.swing.JTextField tf_Auto_Secunadrio;
    private javax.swing.JTextField tf_Autor_Principal;
    private javax.swing.JTextField tf_Editorial;
    private javax.swing.JTextField tf_Genero;
    private javax.swing.JTextField tf_ISBN;
    private javax.swing.JTextField tf_Idioma;
    private javax.swing.JTextField tf_Login_Admin;
    private javax.swing.JTextField tf_Login_Usuario;
    private javax.swing.JTextField tf_Titulo;
    // End of variables declaration//GEN-END:variables
ArrayList usuarios = new ArrayList();
    ArrayList admins = new ArrayList();
    ArrayList libros = new ArrayList();
    int pos;
}
